version: "3.9"

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: svoya-igra-frontend-dev
    ports:
      - "5173:5173" # Откроется на http://localhost:5173
    restart: unless-stopped
